// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhIqUMhOaxFC2Yj4kNu8D9UR5LMj9eDyg',
    appId: '1:939403491775:web:8cb45a51c3e9d9b3db890a',
    messagingSenderId: '939403491775',
    projectId: 'assistant-c6450',
    authDomain: 'assistant-c6450.firebaseapp.com',
    storageBucket: 'assistant-c6450.appspot.com',
    measurementId: 'G-JBGMPKSYY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXQV2ugp7GWpjw2LVBtKacJoolNTK6JVE',
    appId: '1:939403491775:android:8256fe9136a89de1db890a',
    messagingSenderId: '939403491775',
    projectId: 'assistant-c6450',
    storageBucket: 'assistant-c6450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKKG8zmTAb7AGkPiCbejCbSrpz5JJjSZk',
    appId: '1:939403491775:ios:58e2a481eea132a7db890a',
    messagingSenderId: '939403491775',
    projectId: 'assistant-c6450',
    storageBucket: 'assistant-c6450.appspot.com',
    iosBundleId: 'com.example.voiceAssistentFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKKG8zmTAb7AGkPiCbejCbSrpz5JJjSZk',
    appId: '1:939403491775:ios:58e2a481eea132a7db890a',
    messagingSenderId: '939403491775',
    projectId: 'assistant-c6450',
    storageBucket: 'assistant-c6450.appspot.com',
    iosBundleId: 'com.example.voiceAssistentFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhIqUMhOaxFC2Yj4kNu8D9UR5LMj9eDyg',
    appId: '1:939403491775:web:da64f000e0a9d52bdb890a',
    messagingSenderId: '939403491775',
    projectId: 'assistant-c6450',
    authDomain: 'assistant-c6450.firebaseapp.com',
    storageBucket: 'assistant-c6450.appspot.com',
    measurementId: 'G-HHGC3J7G79',
  );
}
